type Code = {
    [index: string]: string;
    0:  string,
    1: string,
    2: string,
    3: string,
    45: string,
    48: string,
    51: string,
    53: string,
    55: string,
    56: string,
    57: string,
    61: string,
    63: string,
    65:string,
    66: string,
    67: string,
    71: string,
    73: string,
    75: string,
    77: string,
    80: string,
    81: string,
    82: string,
    85: string,
    86: string,
    95: string,
    96: string,
    99: string
}

const code : Code = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Drizzle: Light",
    53: "Drizzle: Moderate",
    55: "Drizzle: Intense",
    56: "Freezing Drizzle: Light",
    57: "Freezing Drizzle: Intense",
    61: "Rain: Light",
    63: "Rain: Moderate",
    65: "Rain: Intense",
    66: "Freezing Rain: Light",
    67: "Freezing Rain: Intense",
    71: "Snow fall: Light",
    73: "Snow fall: Moderate",
    75: "Snow fall: Intense",
    77: "Snow grains",
    80: "Rain showers: Light",
    81: "Rain showers: Moderate",
    82: "Rain showers: Intense",
    85: "Snow showers: Light",
    86: "Snow showers: Intense",
    95: "Thunderstorm: Light or moderate",
    96: "Thunderstorm with hail: Light",
    99: "Thunderstorm with hail: Intense"
}

export default code;